import type { LeverFieldMap } from "./ats-field-map";

// Mirrors between_jobs.api.applications_routes._extension_personal_info's
// real response shape exactly (see GET /applications/{id}/extension-payload).
// Deliberately has no work_authorization/dob/nationality/marital_status/
// work_authorization_status/photo fields -- D6, enforced server-side, not
// re-derived here.
export interface ExtensionPersonalInfo {
  name: string;
  email: string | null;
  phone: string | null;
  location: { city: string; region: string; country: string };
  linkedin: string;
  github: string;
  portfolio: string;
}

export interface ExtensionPayload {
  prepare_result: {
    resume?: { artifact_id: string; version_id: string };
    cover_letter?: { artifact_id: string; version_id: string };
  } | null;
  personal_info: ExtensionPersonalInfo | null;
}

/** A generated PDF (résumé or cover letter), base64-encoded for
 * structured-clone transfer across the background <-> content-script
 * message boundary. Fetched by background (the only context allowed to
 * talk to the backend, per this phase's own architecture) once per
 * detection, not per fill click. */
export interface GeneratedFile {
  base64: string;
  filename: string;
}

/** What the background script learns about a tab after the content
 * script reports a detected Lever form and the backend lookup completes.
 * Held in background's own per-tab state map; the side panel and content
 * script both ask for it rather than duplicating the lookup. */
/** E3c -- the verified Lever-idiosyncratic field map, fetched and
 * signature-checked once per detection alongside the résumé/cover-letter
 * blobs (background.ts is the only context that talks to the backend,
 * per this phase's own architecture). `fieldMap: null` means D4's
 * fail-closed case fired -- content.ts must not attempt any Lever-
 * idiosyncratic behavior (custom questions, cover-letter discovery,
 * location/LinkedIn/portfolio) in that case, though the open-source
 * GENERIC_FIELD_DEFAULTS fields (name/email/phone/résumé) remain
 * available regardless, since nothing signed ever backed them.
 * `fieldMapError` carries a human-readable reason for the side panel --
 * distinct states (no map published yet vs. a signature/verification
 * failure vs. a network error) all collapse to the same `null` map, but
 * the reason is still worth showing the person, not just silently
 * degrading. */
export type TabState =
  | { status: "signed_out" }
  | { status: "untracked" }
  | {
      status: "tracked";
      applicationId: string;
      payload: ExtensionPayload;
      resume: GeneratedFile | null;
      coverLetter: GeneratedFile | null;
      fieldMap: LeverFieldMap | null;
      fieldMapError: string | null;
    }
  | { status: "error"; message: string };

/** Content script -> background, on detecting a Lever apply form. */
export interface LeverPageDetectedMessage {
  type: "LEVER_PAGE_DETECTED";
  url: string;
}

/** Side panel -> background: the human clicked "Mark as applied" --
 * tracking-confirmation (browser-extension.md), a new caller of the same
 * `change_application_stage` RPC K1 already built, not new machinery.
 * `idempotencyKey` is generated by the side panel per click (Proposal's
 * own "the caller who can retry owns the key" rule), not by background,
 * so a retried click never double-records the transition. */
export interface MarkAppliedMessage {
  type: "MARK_APPLIED";
  applicationId: string;
  idempotencyKey: string;
}

/** Side panel -> background (E3b, browser-extension.md): check known-
 * question memory before ever drafting anything new -- Proposal §25's
 * own match order, tier 1/2 only (tier 3, semantic matching, is
 * explicitly deferred past v1). `normalizedQuestion` must already be run
 * through `normalizeQuestionLabel` by the caller. */
export interface MatchAnswerMessage {
  type: "MATCH_ANSWER";
  normalizedQuestion: string;
  canonicalIntent?: string;
}

export interface MatchAnswerResult {
  answer: { answer_text: string } | null;
}

/** Side panel -> background: the human approved an answer (drafted or
 * hand-typed) and wants it remembered for next time. */
export interface SaveAnswerMessage {
  type: "SAVE_ANSWER";
  normalizedQuestion: string;
  answerText: string;
}

/** Side panel -> background: draft an answer via the LLM-fallback path.
 * Only ever sent for a `kind: "text"` question the memory check above
 * already missed on -- never for a radio/file field, and never
 * automatically without the human clicking a button first. */
export interface DraftAnswerMessage {
  type: "DRAFT_ANSWER";
  applicationId: string;
  questionText: string;
}

export interface DraftAnswerResult {
  eligible: boolean;
  answer_text: string | null;
  declined_reason: string | null;
  warnings: string[];
}

export type BackgroundMessage =
  | LeverPageDetectedMessage
  | MarkAppliedMessage
  | MatchAnswerMessage
  | SaveAnswerMessage
  | DraftAnswerMessage;

export type MarkAppliedResult =
  | { ok: true; status: string }
  | { ok: false; message: string };

/** Side panel -> content script (direct, via browser.tabs.sendMessage --
 * only the content script can see page DOM state, so it owns detection
 * and fill status; background is purely the backend-API proxy, per
 * browser-extension.md's own architecture: "content script never talks
 * to the backend directly"). */
export type ContentScriptMessage =
  | { type: "GET_DETECTION_STATE" }
  | { type: "RECHECK" }
  | { type: "REQUEST_FILL"; forceRefillAll: boolean }
  | { type: "FILL_FIELD"; fieldName: string; value: string };

export interface FillFieldResult {
  filled: boolean;
}

export interface DetectionStateResponse {
  formDetected: boolean;
  tabState: TabState | null;
}

/** `null` from a REQUEST_FILL response means detection hasn't resolved
 * yet, distinct from a genuine FillResult with everything empty.
 * `fieldMapError` (E3c) is non-null whenever D4's fail-closed case fired
 * for this fill -- cover-letter discovery and custom-question surfacing
 * were skipped entirely, not just left empty, so the side panel can tell
 * "nothing to find" apart from "couldn't check." */
export interface FillResult {
  filledFields: string[];
  skippedFields: string[];
  resumeAttached: boolean;
  resumeError: string | null;
  coverLetterAttached: boolean;
  coverLetterError: string | null;
  unresolvedQuestions: { fieldName: string; label: string | null; kind: "text" | "file" | "radio" }[];
  fieldMapError: string | null;
}
